In [8]:
import pandas as pd

df=pd.read_csv(r"C:\Users\ukesh\OneDrive\Desktop\Project\Ola_Ride_Insights\OLA_DataSet.xlsx - July.csv")
df.head(10)

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 3:15:00,3:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 9:02:00,9:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...
5,2024-07-13 4:42:00,4:42:00,CNR8787177882,Success,CID802429,Mini,Kadugodi,Vijayanagar,231.0,90.0,NaN,NaN,No,NaN,173,UPI,41,3.4,4.6,https://cdn-icons-png.flaticon.com/128/3202/32...
6,2024-07-23 9:51:00,9:51:00,CNR3612067560,Success,CID476071,Bike,Tumkur Road,Whitefield,133.0,40.0,NaN,NaN,No,NaN,140,Cash,49,3.2,4.5,https://cdn-icons-png.flaticon.com/128/9983/99...
7,2024-07-11 11:12:00,11:12:00,CNR5374902489,Canceled by Driver,CID735691,Prime Plus,Bannerghatta Road,Sarjapur Road,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,344,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/11409/1...
8,2024-07-01 19:19:00,19:19:00,CNR5030602354,Driver Not Found,CID999840,Mini,Chamarajpet,Peenya,NaN,NaN,NaN,NaN,NaN,NaN,839,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/3202/32...
9,2024-07-18 1:31:00,1:31:00,CNR6328453219,Canceled by Driver,CID907133,Auto,RT Nagar,Varthur,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,893,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/16526/1...

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  str
 1   Time                        103024 non-null  str
 2   Booking_ID                  103024 non-null  str
 3   Booking_Status              103024 non-null  str
 4   Customer_ID                 103024 non-null  str
 5   Vehicle_Type                103024 non-null  str
 6   Pickup_Location             103024 non-null  str
 7   Drop_Location               103024 non-null  str
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  10499 non-null   str
 11  Canceled_Rides_by_Driver    18434 non-null   str
 12  Incomplete_Rides            63967 non-null   str
 13  Incomplete_Rides_Reason     3926 non-null    str
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              63967 non-null   str
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              103024 non-null  str
dtypes: float64(4), int64(2), str(14)
memory usage: 31.0 MB

In [10]:
df["Date"]=pd.to_datetime(df["Date"])
#df["Time"]=pd.to_datetime(df["Time"],format="%H:%M:%S").dt.time
df["Ride_Distance"]=df["Ride_Distance"].astype(float)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[us]
 1   Time                        103024 non-null  str
 2   Booking_ID                  103024 non-null  str
 3   Booking_Status              103024 non-null  str
 4   Customer_ID                 103024 non-null  str
 5   Vehicle_Type                103024 non-null  str
 6   Pickup_Location             103024 non-null  str
 7   Drop_Location               103024 non-null  str
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  10499 non-null   str
 11  Canceled_Rides_by_Driver    18434 non-null   str
 12  Incomplete_Rides            63967 non-null   str
 13  Incomplete_Rides_Reason     3926 non-null    str
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              63967 non-null   str
 16  Ride_Distance               103024 non-null  float64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              103024 non-null  str
dtypes: datetime64[us](1), float64(5), int64(1), str(13)
memory usage: 29.2 MB

In [11]:
#df["Driver_Ratings"]=df["Driver_Ratings"].fillna(0)
#df["Customer_Rating"]=df["Customer_Rating"].fillna(0)
df["Canceled_Rides_by_Customer"]=df["Canceled_Rides_by_Customer"].fillna("Not Applicable")
df["Canceled_Rides_by_Driver"]=df["Canceled_Rides_by_Driver"].fillna("Not Applicable")
df["Incomplete_Rides"]=df["Incomplete_Rides"].fillna("No")
df["Incomplete_Rides_Reason"]=df["Incomplete_Rides_Reason"].fillna("Not Applicable")
df["V_TAT"]=df["V_TAT"].fillna(0)
df["C_TAT"]=df["C_TAT"].fillna(0)
df["Payment_Method"]=df["Payment_Method"].fillna("Not Applicable")

In [6]:
cancelled_df = df[df["Booking_Status"].str.contains("Canceled", case=False)]

cancelled_df[cancelled_df["Payment_Method"].notnull()]

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,0.0,0.0,Not Applicable,Personal & Car related issue,No,Not Applicable,444,Not Applicable,0.0,0.0,0.0,https://cdn-icons-png.flaticon.com/128/14183/1...
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,0.0,0.0,Driver is not moving towards pickup location,Not Applicable,No,Not Applicable,384,Not Applicable,0.0,0.0,0.0,https://cdn-icons-png.flaticon.com/128/6839/68...
7,2024-07-11 11:12:00,11:12:00,CNR5374902489,Canceled by Driver,CID735691,Prime Plus,Bannerghatta Road,Sarjapur Road,0.0,0.0,Not Applicable,Personal & Car related issue,No,Not Applicable,344,Not Applicable,0.0,0.0,0.0,https://cdn-icons-png.flaticon.com/128/11409/1...
9,2024-07-18 01:31:00,01:31:00,CNR6328453219,Canceled by Driver,CID907133,Auto,RT Nagar,Varthur,0.0,0.0,Not Applicable,Personal & Car related issue,No,Not Applicable,893,Not Applicable,0.0,0.0,0.0,https://cdn-icons-png.flaticon.com/128/16526/1...
13,2024-07-17 18:55:00,18:55:00,CNR3914552212,Canceled by Driver,CID557845,Auto,Hosur Road,Banashankari,0.0,0.0,Not Applicable,Personal & Car related issue,No,Not Applicable,427,Not Applicable,0.0,0.0,0.0,https://cdn-icons-png.flaticon.com/128/16526/1...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102994,2024-07-31 14:27:00,14:27:00,CNR3070763077,Canceled by Customer,CID365812,eBike,Frazer Town,Sarjapur Road,0.0,0.0,Driver asked to cancel,Not Applicable,No,Not Applicable,381,Not Applicable,0.0,0.0,0.0,https://cdn-icons-png.flaticon.com/128/6839/68...
102999,2024-07-31 17:45:00,17:45:00,CNR9658559654,Canceled by Customer,CID896952,Mini,Koramangala,Ramamurthy Nagar,0.0,0.0,Driver is not moving towards pickup location,Not Applicable,No,Not Applicable,269,Not Applicable,0.0,0.0,0.0,https://cdn-icons-png.flaticon.com/128/3202/32...
103001,2024-07-31 01:32:00,01:32:00,CNR3515233519,Canceled by Driver,CID947602,Prime Plus,Langford Town,Vijayanagar,0.0,0.0,Not Applicable,Personal & Car related issue,No,Not Applicable,174,Not Applicable,0.0,0.0,0.0,https://cdn-icons-png.flaticon.com/128/11409/1...
103010,2024-07-31 07:28:00,07:28:00,CNR2746062760,Canceled by Driver,CID323630,Mini,Hulimavu,MG Road,0.0,0.0,Not Applicable,Customer was coughing/sick,No,Not Applicable,487,Not Applicable,0.0,0.0,0.0,https://cdn-icons-png.flaticon.com/128/3202/32...
103015,2024-07-31 17:43:00,17:43:00,CNR1504131542,Canceled by Driver,CID663450,Prime Plus,Bellandur,Hulimavu,0.0,0.0,Not Applicable,Customer related issue,No,Not Applicable,461,Not Applicable,0.0,0.0,0.0,https://cdn-icons-png.flaticon.com/128/11409/1...

In [12]:
df.isna().sum()

Date                              0
Time                              0
Booking_ID                        0
Booking_Status                    0
Customer_ID                       0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
V_TAT                             0
C_TAT                             0
Canceled_Rides_by_Customer        0
Canceled_Rides_by_Driver          0
Incomplete_Rides                  0
Incomplete_Rides_Reason           0
Booking_Value                     0
Payment_Method                    0
Ride_Distance                     0
Driver_Ratings                39057
Customer_Rating               39057
Vehicle Images                    0
dtype: int64

In [13]:
df["Day"]=df["Date"].apply(lambda x: x.day_name())
df["Hour"] = df["Date"].apply(lambda x: x.hour)
df["Is_Ride_Completed"]=((df["Booking_Status"]=="Success") & (df["Incomplete_Rides"]=="No"))

In [14]:
df

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,...,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images,Day,Hour,Is_Ride_Completed
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,0.0,0.0,...,Not Applicable,444,Not Applicable,0.0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...,Friday,14,False
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,...,Not Applicable,158,Cash,13.0,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...,Thursday,22,True
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,...,Not Applicable,386,UPI,40.0,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...,Tuesday,19,True
3,2024-07-22 03:15:00,3:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,0.0,0.0,...,Not Applicable,384,Not Applicable,0.0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...,Monday,3,False
4,2024-07-02 09:02:00,9:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,...,Not Applicable,822,Credit Card,45.0,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...,Tuesday,9,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103019,2024-07-31 09:06:00,9:06:00,CNR9488489435,Success,CID371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,...,Not Applicable,111,Cash,41.0,3.6,3.8,https://cdn-icons-png.flaticon.com/128/11409/1...,Wednesday,9,True
103020,2024-07-31 15:12:00,15:12:00,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,...,Not Applicable,1097,UPI,17.0,4.3,3.3,https://cdn-icons-png.flaticon.com/128/16526/1...,Wednesday,15,True
103021,2024-07-31 13:59:00,13:59:00,CNR1286151233,Success,CID113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,...,Not Applicable,2201,Cash,37.0,3.6,3.2,https://cdn-icons-png.flaticon.com/128/9983/99...,Wednesday,13,True
103022,2024-07-31 14:56:00,14:56:00,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,210.0,140.0,...,Not Applicable,267,UPI,47.0,3.4,3.1,https://cdn-icons-png.flaticon.com/128/6839/68...,Wednesday,14,True
103023,2024-07-31 13:57:00,13:57:00,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,175.0,125.0,...,Not Applicable,462,UPI,3.0,4.8,4.4,https://cdn-icons-png.flaticon.com/128/16526/1...,Wednesday,13,True

In [11]:
pip install sqlalchemy pymysql

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.51-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Collecting pymysql
  Using cached pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.2-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in .\.venv\Lib\site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.0.51-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ------------------------ --------------- 1.3/2.1 MB 5.2 MB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 4.0 MB/s  0:00:00
Using cached pymysql-1.2.0-py3-none-any.whl (45 kB)
Downloading greenlet-3.5.2-cp312-cp312-win_amd64.whl (239 kB)
Installing collected packages: pymysql, greenlet, sqlalchemy

   ---------------------------------------- 0/3 [pymysql]
   ---------------------------------------- 0/3 [pymysql]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.5.2 pymysql-1.2.0 sqlalchemy-2.0.51
Note: you may need to restart the kernel to use updated packages.

In [15]:
from sqlalchemy import create_engine

username="root"
password="12345678"
host="localhost"
port="3306"
database="OLA_Ride_Analysis"

engine=create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

In [16]:
df.to_sql(
    name="ola_data",
    con=engine,
    if_exists="replace",
    index=False
)

103024

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 23 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[us]
 1   Time                        103024 non-null  str
 2   Booking_ID                  103024 non-null  str
 3   Booking_Status              103024 non-null  str
 4   Customer_ID                 103024 non-null  str
 5   Vehicle_Type                103024 non-null  str
 6   Pickup_Location             103024 non-null  str
 7   Drop_Location               103024 non-null  str
 8   V_TAT                       103024 non-null  float64
 9   C_TAT                       103024 non-null  float64
 10  Canceled_Rides_by_Customer  103024 non-null  str
 11  Canceled_Rides_by_Driver    103024 non-null  str
 12  Incomplete_Rides            103024 non-null  str
 13  Incomplete_Rides_Reason     103024 non-null  str
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              103024 non-null  str
 16  Ride_Distance               103024 non-null  float64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              103024 non-null  str
 20  Day                         103024 non-null  str
 21  Hour                        103024 non-null  int64
 22  Is_Ride_Completed           103024 non-null  bool
dtypes: bool(1), datetime64[us](1), float64(5), int64(2), str(14)
memory usage: 35.7 MB